
all:

	x86_64-w64-mingw32-g++ -std=c++11 src/lameEngine.cpp inc/lame.h lib/64bit/* -o bin/wav2mp3-64.exe
	i686-w64-mingw32-g++ -std=c++11 src/lameEngine.cpp inc/lame.h lib/32bit/* -o bin/wav2mp3-32.exe
